INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Java para Web', 'Willian Santos', FALSE, NULL);
INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Spring Boot na Prática', 'Jeff', FALSE, NULL);
INSERT INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Arquitetura REST', 'Luiz Eduardo', TRUE, '2026-03-01');


